EyeSeeTea/user-extended-app

package.json

fix npm installation failure because `babel` is deprecated in favor of `babel-cli`

fix(dependecy) update babel to bable-cli

---

includes/feedback-tool/feedback-dhis2.js

Closes #59 
When getting translations with `fetch`, we must use `credentials: 'include'` so it works on production.
Documentation:
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#Sending_a_request_with_credentials_included

Fetch translations with same-origin credentials to avoid 302

---

src/components/MultiSelect.component.js

= PR. Pull request template
* **Issue:** Closes #101
- Pass `filterText` from `MultiSelect` to `GroupEditor`.

Add missing prop filterText for roles/groups modal filters

---

src/List/List.component.js

* **Issue:** Closes #103 
- Currently we were using `displayName:ilike:STRING`. Now we use the specific `query` param for `/users`, which performs an insensitive search over fields _username,_ _firstName_, _surname_ and _email_: 
https://docs.dhis2.org/2.29/en/developer/html/dhis2_developer_manual_full.html#webapi_users_query

Use query param for a more general text filter

---

src/List/context.actions.js

* **Issue:** Closes #100 
- Get current Dhis2 version from: `d2.system.version`.
- <= 2.29 uses the old app with list filter /dhis-web-maintenance-user/alluser.action?key=USERNAME, >= 2.30 uses /dhis-web-user/index.html#/users/edit/ID

Fix edit action for >= 2.30

---

src/components/ImportTable.component.js

* **Issue:** Closes #119 
- Set `overflow: visible` for table wrapper

Show horizontal scroll bar on import table wrapper

---

src/components/Share.component.js

Fixes sharing wrapper styles. Before:

Set Share wrapper to fixed position

---

src/models/userHelpers.js

* **Issue:** Closes #143 
HWF (NHWA) users complained that the lastLogin date was defaulting to the same day of the export, this was happening because we were executing ```moment(undefined)``` which creates a ```new Date()```.
This fixes this issue for lastLogin, lastUpdated and created fields.

Do not export last login date if not defined

---

package.json
src/components/ImportTable.component.js
src/models/user.js

- Add to ``User.getById`` the fields of organisationUnits attributes
- Send to component templateUser's ```organisationUnits``` and ```dataViewOrganisationUnits``` attributes.
[User-Extended-App.zip](https://github.com/EyeSeeTea/user-extended-app/files/3601456/User-Extended-App.zip)

Show existing OU in replicate user

---

src/models/userHelpers.js

- The original code had a work-around to make the request work in DHIS2 version pre 2.30
- Yet the work-around introduces a bug when there are too many users included in the filtering
- Also from my testing it appears that the work-around does not work as expected
*Temporal fix*
- If version is 2.30+, ignore the work-around and proceed with a bug-less request
*Open discussion*
- How do we properly fix this?
- Was the work-around really needed?
*For context*
```
/*  Filtering over nested fields (table[.table].field) in N-to-N relationships (for
example: userCredentials.userRoles.id), fails in dhis2 < v2.30. So we need to make
separate calls to the API for those filters and use the returned IDs to build
the final, paginated call. */
```

[HWF] Fix issue when filter includes too much users

---

src/List/context.actions.js

Tested with one user and removed in another tab the authorities and it appears to be working fine os far. The change is very small and more restrictive than what we had before.

Check for correct authority with replicate user

---

src/models/userHelpers.js

This was hard to debug, even though our logic manually merged the CSV built user with the existing user during import, we had a bug with collections (userGroups/userRoles/organisationUnits/dataViewOrganisationUnits) that were defaulting to an empty collection instead of undefined.
- Export some users without "Organisation Units" column
- Import these users
**Expected behavior**
- Users should have kept the original organisation unit assignment
**Actual behavior**
- Users have lost their assignment to the organisation unit
NOTE: The case where you have the column and no OU assigned has always worked

Do not clear collections on import

---

package.json
src/components/UserRolesDialog.component.js

* **Issue:** Closes #167 
- Add column "last login" to table (to see the bug happening)
- Select an user that has previously logged in
- Do any change in the user roles (assign a new one for example)
- The user's last login date has been cleared from the database
- Fetch lastLogin field as "parent" and use it in the resulting user payload
- The current implementation uses a REPLACE strategy but we do not fetch all properties (So not only lastLogin but other fields might get lost.
- Since "it is working" just fine for now I would not touch it more than this.
- If we have time, a more robust approach could be implemented but it would require some hours.

Do not clear lastLogin date on updating user roles

---

app-config/app-config.example.json
package.json
src/App/appStateStore.js
src/List/List.component.js
src/List/context.actions.js
src/components/ImportTable.component.js
src/components/OrgUnitForm.js
src/components/ReplicateUserFromTable.component.js
src/components/ReplicateUserFromTemplate.component.js
src/i18n/i18n_module_ar.properties
src/i18n/i18n_module_en.properties
src/i18n/i18n_module_es.properties
src/i18n/i18n_module_fr.properties
src/models/settings.js
src/models/user.js
src/models/userHelpers.js

Closes #177 
Requires https://github.com/EyeSeeTea/d2-ui/pull/28
Notes:
- Use only `orgUnit.shortName` except for importing, where we match both by shortName and displayName (this way old csv export files will still work)
- A user with a setting orgUnitField="displayName" will now show "shortName" without a need for migration (as it's the default value).

Use organisation units short name

---

package.json
src/components/batch-models-multi-select/CopyInUserBatchModelsMultiSelect.component.js
src/components/batch-models-multi-select/CopyInUserBatchModelsMultiSelect.model.js
src/models/userHelpers.js

-   **Issue:** Closes "Add option to copy data view and data capture org unit" in ClickUp (CU-d112tv)
- Added 2 new toggles for orgUnits and OU Outputs
- added a boolean for the toggles to pass it to the copyInUserSave function 
- Extended the getPayload function to copy over orgUnits in the same fashion as userGroups and userRoles

Add option to copy data view and data capture org unit

---

src/List/Filters.component.js

-   **Issue:** Closes ["Paging error filtering by group"](https://app.clickup.com/t/dn075t) in ClickUp  and issue [#41](https://github.com/EyeSeeTea/user-extended-app-blessed/issues/41)
- The issue was that in the API call if there was no searchString in the query it would only return the first page of results instead of all results so I just changed it so that if there is a searchString you add the query param else don't
For this example now it shows all 60 users instead of stopping at 50, the page limit

Workaround for paging error when filtering by group

---

src/components/batch-models-multi-select/CopyInUserBatchModelsMultiSelect.component.js
src/components/batch-models-multi-select/CopyInUserBatchModelsMultiSelect.model.js
src/models/userHelpers.js

-   **Issue:** Closes ["Add strategy to copy in user feature"](https://app.clickup.com/t/dn0840) in ClickUp
- Added Replace/Merge toggle in top right and moved property toggles to bottom left
- In getPayload in userHelpers I passed the updateStrategy chosen to the addItems function so if it is chosen as "Replace" then it will just return the parent version of that property. 
- I then had to create a sort of new version of saveUsers in saveCopyInUsers where it got the existing users so it overrode their values.

Add strategy to copy in user feature. 

---

src/components/batch-models-multi-select/CopyInUserBatchModelsMultiSelect.component.js
src/components/batch-models-multi-select/CopyInUserBatchModelsMultiSelect.model.js

-   **Issue:** Closes ["Add more descriptive information in copy in user"](https://app.clickup.com/t/k56xzq) in ClickUp
- Added "userCredentials[username] into childrenFields in CopyInUserBatchModelsMultiSelect.model and added it to the options array of objects so it would show in the users that you see in CopyInUser

Add more descriptive information in copy in user

---

src/List/list.store.js
src/components/ImportExport.component.js
src/components/OrgUnitsFilter.component.js
src/models/userHelpers.js

Closes https://app.clickup.com/t/md946f, https://app.clickup.com/t/md94hf
- [Export] exports only visible columns. 
- [Export template] exports all columns. Now, we add `password` and remove `["lastUpdated", "created", "lastLogin"]`, which don't seem to make much sense later when importing. It's easy to change: [here](https://github.com/EyeSeeTea/user-extended-app/pull/204/files#diff-cc9b1afc37b6e4370c7578a3cec9b843fa6a123d611bdd6876e78bc8b64e0ee0R543).
- Tested: On import, password column is used to build the import UI table.
- Fixed missing translations in orgUnits pop-up filters.

Refactor exportTemplateToCsv with custom columns

---

package.json
src/models/userList.js

Closes https://app.clickup.com/t/mn8uhh
The problem when page > 1 showing only 1 user forbids using the default DHIS2 call altogether. So we must use always custom queries, slower.

Use always custom query/filters

---

public/old-i18n/i18n_module_ar.properties
public/old-i18n/i18n_module_en.properties
public/old-i18n/i18n_module_es.properties
public/old-i18n/i18n_module_fr.properties
src/legacy/List/Filters.component.js

-   **Issue:** https://app.clickup.com/t/2cbz4q8
Add a switch button to the "Advanced filters" sub-screen that changes the state of `this.state.rootJunction`.
`this.state.rootJunction === false` means AND filtering and `this.state.rootJunction === true` means OR.

Feature/Implement interface for selecting AND or OR filtering behavior

---

src/legacy/List/List.component.js
src/webapp/components/user-list-table/UserListTable.tsx

-   **Issue:** https://app.clickup.com/t/2f1tj5j
The `src/legacy/components/ImportExport.component.js` property `filterOptions` was missing the filter by name query, that's why the filter was not applied to the export.

[User-Extended] Apply filters to the export function

---

src/data/models/UserModel.ts
src/data/repositories/UserD2ApiRepository.ts
src/domain/entities/User.ts
src/webapp/components/user-form/UserForm.tsx
src/webapp/components/user-form/utils.ts

This way, when we update a user we do not send an empty value for accountExpiry.
Dhis2 interprets now an empty value as setting it to its first date, 1970-01-01, and that stops the users from being able to connect (since the date is in the past).
-   **Issue:** Closes https://app.clickup.com/t/3jv4b34
Commented out all appearances of `accountExpiry`.
In the POST request when modifying a user, there is no `accountExpiry` anymore (and thus dhis2 doesn't set it to 1970).

Comment out all uses of accountExpiry.

---

src/legacy/List/organisation-unit-dialog/OrgUnitDialog.component.js
src/webapp/components/user-form/components/OrgUnitSelectorFF.tsx

-   **Issue:** Closes https://app.clickup.com/t/2ghev8r
Trivial. Just added `showNameSetting={true}` to the OrgUnitsSelector component in the OrgUnitDialog component and the OrgUnitSelectorFF component.
When clicking on "Assign to organisation units":
When clicking on "Assign to data view organisation units":
When editing a user:

Use switch to show short names in all uses of the OrgUnitsSelector component

---

src/data/repositories/UserD2ApiRepository.ts
src/domain/repositories/UserRepository.ts
src/legacy/List/List.component.js
src/webapp/components/user-list-table/UserListTable.tsx

-   **Issue:** https://app.clickup.com/t/2jefv4d
Added the `canManage` query and fixed the user list paging issues (the total users value updated inconsistently).

Bugfix/"Display only users I can manage" filter not working

---

src/data/repositories/UserD2ApiRepository.ts
src/legacy/models/userHelpers.js

-   **Issue:** Closes https://app.clickup.com/t/860r74hyd
In version 2.38.1.1 in order to update **openId** and **passwords** must be added outside **userCredentials** object.

include openid and password outside userCredentials

---

src/data/models/UserModel.ts
src/data/repositories/UserD2ApiRepository.ts

-   **Issue:** Closes https://app.clickup.com/t/865cqfvdf
Including user `id` inside `userCredentials` to keep compatibility with version 2.37.9.1.
Also tested on 2.36.13 and 2.38.4

include user id inside userCredentials object

---

src/webapp/components/multi-selector-dialog/MultiSelectorDialog.tsx

-   **Issue:** Closes [Assigning roles while a filter is applied deletes all assigned roles](https://app.clickup.com/t/8693eg2c4)
- Simplify messy logic and fix bug assigning roles with filter
[screen-capture (2).webm](https://github.com/EyeSeeTea/user-extended-app/assets/44171664/8d075172-f925-4f43-b1ba-d4ba50f6a047)

Fix assign roles filter bug, simplify component

---

src/data/repositories/UserD2ApiRepository.ts
src/webapp/components/user-list-table/UserListTable.tsx

-   **Issue:** Closes https://app.clickup.com/t/865bp4tzy
Skipping saving columns in `userDataStore` if the table components sends an empty array for columns. Showing the default columns if an empty array is found in `userDataStore` (for existing users affected by the error)
Replicating this error is very difficult, but you can simulate it by saving an empty array into the `userDataStore`
```bash
curl -u USER:PWD --location --request PUT 'http://localhost:8080/api/userDataStore/user-extended-app/visible-columns' \
--header 'Content-Type: application/json' \
--data '[]'
```
if you go to the app you will see the default columns

avoid saving columns if value is empty

---

src/legacy/components/ReplicateUserFromTable.component.js
src/legacy/components/ReplicateUserFromTemplate.component.js

-   **Issue:** Closes [[User-Extended App] - Errors when replicating users are not caught and shown, but instead, a big json file is thrown](https://app.clickup.com/t/8693ncwng)
- Use snackbar to show a simpler error message.

Show simpler 'replicate user' error message

---

i18n/es.po
src/types/i18n.d.ts
src/webapp/components/user-list-table/UserListTable.tsx
src/webapp/contexts/app-context.ts

-   **Issue:** Closes https://app.clickup.com/t/86944c81y
Feedback component was overriding the namespace translation. This PR is forcing to use the app namespace. At the beginning I though we needed [an update of feedback-component](https://github.com/EyeSeeTea/feedback-component/pull/4), but it's not really necessary.
Spanish translations
- Go to user settings http://localhost:8080/dhis-web-user-profile/#/settings
- Change interface language to spanish
- Test
86944c81y

force i18n namespace in appContext

---

.github/workflows/main.yml
src/react-app-env.d.ts

-   **Issue:** https://app.clickup.com/t/8694ekvck
- 8694ekvck
Since we add unit tests it could be nice to fire them when we push.
You can use [act](https://nektosact.com/introduction.html) to test it locally with `act -n`

chore: add CI workflow on push (localize, jest, tsc)

---

src/data/repositories/UserD2ApiRepository.ts
src/legacy/models/userHelpers.js
src/webapp/hooks/userHooks.ts

-   **Issue:** Closes https://app.clickup.com/t/8694vdgyw
Select any user and edit roles from the `Edit page` or the `Assign roles` action from the table.
#8694vdgyw

include timestamp to url to avoid cache

---

src/legacy/models/userHelpers.js
src/webapp/hooks/userHooks.ts

-   **Issue:** Closes https://app.clickup.com/t/8694vdgyw
#8694vdgyw

get groups information from userGroups endpoint

---

src/legacy/models/userHelpers.js

-   **Issue:** Closes [[User feedback] Cannot update users from CSV](https://app.clickup.com/t/8695ujvwy)
In DHIS 2.37 the API POST to `api/metadata` fails because the provided user objects lack the `userCredentials` property.
This issue doesn't happen in DHIS2.38.
The proposed solution until this feature gets refactored is to use the `usersToSave` variable as the payload.
This variable contains the user metadata merged with the import changes in case of overwrite and a minimal user object in case of creating a new one.
In the debugging process the following bugs were identified:
- Capture OrgUnits was not a mandatory field in the import table, it is in the User App. It was added as a required property.
- The import process allows creating users without roles or Capture OrgUnits. There is …

Fix: CSV import fails in DHIS2.37 due to missing userCredentials.

---

i18n/en.pot
i18n/es.po
src/data/models/DHIS2Model.ts
src/data/repositories/UserD2ApiRepository.ts
src/domain/usecases/ImportUsersUseCase.ts
src/legacy/models/userHelpers.js
src/webapp/components/form/fields/TransferFF.tsx
src/webapp/components/import-export/ImportTable.tsx
src/webapp/components/user-form/components/OrgUnitSelectorFF.tsx

-   **Issue:** Closes [[User feedback] Cannot update users from CSV](https://app.clickup.com/t/8695ujvwy)
After the merging of #295, a number bugs were discovered with the new table, aside of the one mentioned [here](https://github.com/EyeSeeTea/user-extended-app/pull/302#issuecomment-2401951394).
- The "Overwrite existing users" switch didn't trigger a new validation of the form, leading to the "Import" button to be unresponsive.
- When a user was imported without search or dataView OUs the import failed with "POST 409" due to an incorrect transformation of emptyOrgUnit (entity) into an empty OU for data. This issue also happened when the instance OU doesn't have a code (its not mandatory).
- A new user could be imported with an empty password field.
- When a user was imported with empty …

Fix: CSV import removes existing userGroups memberships
