src/List/List.component.js
src/components/RichDropdown.component.js

Use rich dropdown for filters role/group with search bar

---

src/App/App.component.js

Closes #52 
(Requires https://github.com/EyeSeeTea/d2-ui/pull/18)

Add styles and app name to header bar

---

src/List/List.component.js
src/List/list.actions.js
src/List/list.store.js

Keep filters applied on page change

---

src/List/DetailsBox.component.js
src/List/list.store.js

= PR. Pull request template
* **Issue:** Closes #94 
- Added lastLogin and userRoles to fields to display.
- When collection is empty, show "No value" (in italics)

Show lastLogin and userRoles fields in details box

---

src/List/organisation-unit-dialog/OrgUnitDialog.component.js
src/components/OrgUnitsFilter.component.js

Fixes https://github.com/EyeSeeTea/user-extended-app-blessed/issues/22

Enable intersection policy for orgUnits filter and setter

---

src/components/ReplicateUserFromTable.component.js
src/models/user.js

* **Issues:** Closes #149 
Ideally we would support the columns that we show in the modal with an option. Maybe for a future iteration of the application.

[HWF] Allow setting custom OUs on user replication

---

src/List/organisation-unit-dialog/OrgUnitDialog.component.js

Fixes #175 
- The error was present already at 2.32
- Fix tested with 2.30, 2.32, 2.34.

Send userCredentials on set orgUnits payload

---

src/components/UserRolesDialog.component.js
src/components/batch-models-multi-select/BatchModelsMultiSelect.model.js
src/components/batch-models-multi-select/CopyInUserBatchModelsMultiSelect.component.js
src/components/batch-models-multi-select/CopyInUserBatchModelsMultiSelect.model.js
src/models/userHelpers.js

-   **Issue:** Closes ["Bug adding roles to disabled user"](https://app.clickup.com/t/eh62xm) in ClickUp
- The issue was that when copying the userRoles for some reason some properties of userCredentials aren't passed when getting the user so I had to add that user's disabled property to send to the payload
- All I had to do was add "disabled" to the parentFields in the modelOptions in userRolesDialog

bug fix adding roles to disabled users

---

.env
src/domain/repositories/UserRepository.ts
src/legacy/List/List.component.js
src/legacy/components/CopyInUserDialog.component.js
src/legacy/components/batch-models-multi-select/CopyInUserBatchModelsMultiSelect.component.js
src/legacy/components/batch-models-multi-select/CopyInUserBatchModelsMultiSelect.model.js
src/legacy/models/userHelpers.js
src/webapp/components/user-list-table/UserListTable.tsx

-   **Issue:** Part 1 of ?? in [[User-Extended] Review all contextual actions if they work or not, fix old code to make them work again](https://app.clickup.com/t/1fzw77u) in ClickUp. Fixing the Copy In User functionality.
- Now the users are passed as an array so I modified the PropTypes and took out user destructuring in CopyInUserDialog.component.js since that is not necessary anymore
- There was a mismatch between OrgUnits and OrgUnitOutputs. I thought in the previous fixes in user-extended-app we changed the names to be OU Capture and OU Output. 
- Parent is passed as an string id now instead of object in CopyInUserBatchModelsMultiSelect.component.js and CopyInUserBatchModelsMultiSelect.model.js so I removed some lodash things to get the ids.
- Improved typing of filters from …

[Refactor] Fix Copy In User New

---

package.json
src/CompositionRoot.ts
src/data/repositories/UserD2ApiRepository.ts
src/domain/repositories/UserRepository.ts
src/domain/usecases/ListAllUserIdsUseCase.ts
src/webapp/components/user-list-table/UserListTable.tsx
yarn.lock

-   **Issue:** https://app.clickup.com/t/1hyvu51

[Feature] Select in all ids

---

i18n/en.pot
i18n/es.po
src/legacy/components/ImportTable.component.js
src/legacy/components/InfoDialog.js
src/legacy/components/MultipleSelector.component.js
src/legacy/components/ReplicateUserFromTable.component.js
src/legacy/components/ReplicateUserFromTemplate.component.js

-   **Issue:** https://app.clickup.com/t/1t1ynpf
- Switched to ConfirmationDialog instead of Dialog on ImportTable and MultipleSelector
- The ImportTable toggle is not inline with the buttons as the new component has a different layout. The toggle is placed closest to where it was before

Replace Dialog with ConfirmationDialog, part 2

---

src/data/clients/storage/DataStoreStorageClient.ts
src/data/clients/storage/Namespaces.ts
src/data/clients/storage/StorageClient.ts

-   **Issue:** Closes https://app.clickup.com/t/1p2bhj2

[Feature] Add storage client futures

---

i18n/en.pot
i18n/es.po
src/data/repositories/UserD2ApiRepository.ts
src/webapp/components/multi-selector-dialog/MultiSelectorDialog.tsx

-   **Issue:** Fixes #224 
Reset loading on error. Fix on removing roles/group.

[Fix] Replace MultiSelectors with Transfers

---

src/webapp/components/multi-selector-dialog/MultiSelectorDialog.tsx

-   **Issue:** Closes https://app.clickup.com/t/1y29v8p

fix bug with transfer component

---

src/legacy/List/context.actions.js

-   **Issue:** Closes https://app.clickup.com/t/3dehavc

fix assign to org units error

---

package.json
src/data/repositories/UserD2ApiRepository.ts
src/legacy/List/List.component.js
src/legacy/models/userHelpers.js
src/webapp/components/user-list-table/UserListTable.tsx

-   **Issue:** [Bug on user-Extended app for user creation/modification](https://app.clickup.com/t/860q01d6x)
- Fix user edit not working in 2.38 (still broken in 2.36, gives error 500)
- Fix import missing some fields
- Disable new user button as this function doesn't work.

Fix empty userRoles POST when using the edit page

---

src/legacy/models/userHelpers.js

-   **Issue:** Closes https://app.clickup.com/t/860r74hyd
Original bug about importing passwords cannot be replicated, but we found a bug related to the export process (which is a common previous step for import) so this PR includes the fix.

Validate if user has roles, groups or OUS in export process

---

package.json

- Export to CSV function fixed

Release 1.3.1

---

package.json
src/data/repositories/UserD2ApiRepository.ts
src/legacy/components/OrgUnitForm.js
src/legacy/models/userHelpers.js
src/webapp/pages/about/AboutPage.tsx

- Include openID and password outside userCredentials to keep compatibility with 2.38.1 DHIS2 builds
- Fix OU tree selection in CSV import

Release 1.3.2

---

.github/pull_request_template.md
package.json
src/data/models/UserModel.ts
src/data/repositories/UserD2ApiRepository.ts

Release 1.3.3

---

package.json
src/legacy/List/List.component.js
src/legacy/components/ImportTable.component.js
src/legacy/components/MultipleSelector.component.js
src/legacy/components/OrgUnitsSelectorFilter.js
src/utils/d2-api.ts
src/webapp/components/user-form/components/OrgUnitSelectorFF.tsx
yarn.lock

-   **Issue:** Closes https://app.clickup.com/t/860ryr9a0
**Switch ON**
**Switch OFF**

update d2-ui-components to 2.7.0_beta.2

---

src/data/models/UserModel.ts
src/data/repositories/UserD2ApiRepository.ts

-   **Issue:** Closes https://app.clickup.com/t/8693e3wam
#8693e3wam

include created/updated by in userCredentials for version 236

---

i18n/en.pot
i18n/es.po
src/data/models/UserModel.ts
src/data/repositories/UserD2ApiRepository.ts
src/domain/entities/User.ts
src/legacy/List/list.store.js
src/legacy/models/userHelpers.js
src/legacy/models/userList.js
src/webapp/components/user-list-table/UserListTable.tsx

**Issue:** Closes 
- https://app.clickup.com/t/8694b65wt
- https://app.clickup.com/t/8694ba046
https://github.com/EyeSeeTea/user-extended-app/assets/37223065/c2aa52f6-e203-432f-9cde-d57d9ed25e85
#8694b65wt
#8694ba046

add columns to user list table

---

src/legacy/models/userHelpers.js

-   **Issue:** Closes https://app.clickup.com/t/8694ba21z
https://github.com/EyeSeeTea/user-extended-app/assets/37223065/a50cf46d-5865-4c97-84bb-634d5463bff5
Import a CSV file with no Roles field
#8694ba21z

require userRoles on import

---

package.json
src/domain/usecases/__tests__/SaveUserOrgUnitUseCase.spec.ts
src/domain/usecases/__tests__/data/user.ts
yarn.lock

-   **Issue:** https://app.clickup.com/t/8694ekvck
- 8694ekvck
- `ts-mockito` installed
- test on `SaveUserOrgUnitUseCase`
To launch the specific test `yarn test SaveUserOrgUnitUseCase.spec.ts`

chore: add test for `SaveUserOrgUnitUseCase`

---

src/webapp/components/form/fields/PreviewInputFF.tsx
src/webapp/components/user-edit-wizard/UserEditWizard.tsx
src/webapp/utils/list.ts

-   **Issue:** Closes https://app.clickup.com/t/86944c81y

update i18n imports on edit page

---

i18n/en.pot
i18n/es.po
package.json
src/data/repositories/UserD2ApiRepository.ts
src/legacy/models/userHelpers.js
src/webapp/components/form/fields/PreviewInputFF.tsx
src/webapp/components/user-edit-wizard/UserEditWizard.tsx
src/webapp/utils/list.ts

Release 1.5.2
